spring:
  datasource:
    url: jdbc:h2:mem:user_db
    password: password
    username: sa

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true


server:
  port: 9090

